Use CLBlast instead of clBLAS
primitiv/primitiv pull request #143
Opened 2018-01-06 13:34 UTC by vbkaisetsu

This branch uses CLBlast instead of clBLAS in OpenCL device.

It is mainly for reducing dependencies. clBLAS requires Boost that is a large library, so it's difficult to adapt to multiple operating systems and devices.
CLBlast does not require additional library, so it is portable.

CLBlast keeps performance in my experiments.

2018-01-07 07:05 UTC, odashi requested changes

2018-01-07 07:05 UTC, odashi commented on cmake/FindCLBlast.cmake
> +# - Try to find CLBlast lib
Not enough documentation. Describe all possible options and license.

2018-01-07 13:50 UTC, odashi commented
The CLBlast prerequisite should be documented in all existing documents (we've also forgotten to add clBLAS prerequisites in current documents).

2018-03-03 08:52 UTC, vbkaisetsu commented
I rewrote `FindCLBlast.cmake` based on `FindPrimitiv.cmake`, and fixed documentation.
Please review it.

2018-03-04 22:25 UTC, odashi commented on docs/source/installation.rst
> +Installing CLHPP
Installing OpenCL C++ Headers

2018-03-04 22:25 UTC, odashi commented on docs/source/installation.rst
> +OpenCL backend requires OpenCL C++ headers (CLHPP) and CLBlast.
Probably not necessary. Prerequisites are already documented in previous sections.

2018-03-04 22:25 UTC, odashi commented on docs/source/installation.rst
> +  $ cmake .. [OPTIONS]  # See: https://github.com/KhronosGroup/OpenCL-CLHPP
Fix comment.

2018-03-04 22:25 UTC, odashi commented on docs/source/installation.rst
> +The following command configures to build OpenCL backend using
OpenCL backend -> the OpenCL backend

2018-03-04 23:14 UTC, vbkaisetsu commented
Fixed.

2018-03-05 08:05 UTC, odashi approved these changes

2018-03-05 08:05 UTC, merged