Add new functions to support ANDROID
primitiv/primitiv pull request #144
Opened 2018-01-06 13:44 UTC by vbkaisetsu

ANDROID's libstdc++ does not have `std::to_string()`.

This branch adds `string_utils::to_string()` functions that simulates behavior of `std::to_string()` on ANDROID.

2018-01-07 05:52 UTC, odashi requested changes
See following page and fix code.

https://cpprefjp.github.io/reference/string/to_string.html

Then we become not to need `std::to_string()` wherever we want to convert numericals to strings.

2018-01-07 07:08 UTC, odashi requested changes
And there is no test code.

2018-01-07 14:25 UTC, vbkaisetsu commented
Fixed.

2018-01-07 14:37 UTC, odashi requested changes

2018-01-07 14:37 UTC, odashi commented on primitiv/string_utils.h
> + * These functions support them.
What is *them*?

2018-01-07 14:37 UTC, odashi commented on primitiv/string_utils.h
> +   * max uint32_t = 4294967295
Probably redundant. Line 45 has enough information.

2018-01-07 14:37 UTC, odashi commented on primitiv/string_utils.h
> +   * buffer's size = (digits10 + 1) + NULL
`NULL` can be used to only pointers. Should describe `'\0'` in this case.

2018-01-07 14:37 UTC, odashi commented on primitiv/string_utils.h
> +   * max float = 340282346638528859811704183484516925440.000000
ditto

2018-01-07 14:37 UTC, odashi commented on test/string_utils_test.cc
> +            to_string(340282346638528859811704183484516925440.0f)); // max float
Use `numeric_limits`.

2018-01-07 14:58 UTC, vbkaisetsu commented
Fixed.

2018-01-07 15:30 UTC, odashi commented on primitiv/string_utils.h
> +#include <primitiv/error.h>
Unnecessary include.

2018-01-07 15:35 UTC, odashi commented
Maybe it is better to implement `to_string()` of all types:

- `int` and `unsigned`
- `long` and `unsigned long`
- `long long` and `unsigned long long`
- `float`, `double` and `long double`

Otherwise, calling this function may accidentally perform implicit type conversions to available types

2018-01-07 15:38 UTC, odashi commented on test/string_utils_test.cc
> +  EXPECT_EQ("4294967295", to_string(0xffffffffu)); // max uint32_t
Also should be `numeric_limits`.

2018-01-08 03:15 UTC, vbkaisetsu commented
I wrote behaviour of `to_string()` for all types including `long double`. However, the size of `long double` may be different on architectures, so I wrote test cases of `to_string(long double)` only for some 64bit systems.

2018-01-08 05:12 UTC, odashi commented
Usually, **all** floating point types (including even `float` and `double`) are *implementation-defined*, and we can not write always correct tests for such types. I think the most reliable way of tests is determining length of resulting strings using `max_exponent10`.

2018-01-08 05:17 UTC, odashi requested changes

2018-01-08 05:17 UTC, odashi commented on primitiv/string_utils.h
> +#define DEF_TO_STRING(type, format, size) \
I don't recommended to use macros in general headers.

2018-01-08 06:10 UTC, odashi requested changes

2018-01-08 06:10 UTC, odashi commented on test/string_utils_test.cc
> +#if __x86_64__ || __ppc64__
Use `#if defined`.

2018-01-08 06:10 UTC, odashi commented on test/string_utils_test.cc
> +#endif  // __x86_64__ || __ppc64__
Fix comment.

2018-01-08 06:10 UTC, odashi commented on test/string_utils_test.cc
> +  /*
Redundant comment. The content is completely same as above condition.

2018-01-08 06:10 UTC, odashi commented on test/string_utils_test.cc
> +#if __x86_64__ || __ppc64__
ditto

2018-01-08 06:10 UTC, odashi commented on test/string_utils_test.cc
> +#endif  // __x86_64__ || __ppc64__
ditto

2018-01-08 06:13 UTC, odashi commented
However current tests looks enough for usual systems, and I'll merge this branch after solving comments.

2018-01-08 17:18 UTC, odashi requested changes

2018-01-08 17:18 UTC, odashi commented on test/string_utils_test.cc
> +  EXPECT_EQ("118973149535723176502126385303097020516906332229462420044032373"
This string literal is identical with that about the minimum value except the top `"-"` character, and both can be integrated into one string literal. Also `float` and `double` string literals can be integrated into one.

2018-01-08 17:32 UTC, odashi commented on primitiv/string_utils.h
> +    char buffer[std::numeric_limits<type>::size]; \
This array consumes a huge space of the stack (especially when converting from `long double`) that is usually not recommended. But using dynamic arrays (e.g., `vector`) requires some heap allocations. I have no good idea to fix this.

2018-01-09 04:51 UTC, odashi approved these changes

2018-01-09 05:34 UTC, merged