Support 32 bit architectures
primitiv/primitiv pull request #174
Opened 2018-03-09 11:13 UTC by vbkaisetsu

This branch adds some compile switches to support 32 bit architectures, and adds a Travis CI script to run test cases on the i386 architecture.

2018-03-25 03:13 UTC, odashi requested changes

2018-03-25 03:13 UTC, odashi commented on primitiv/model.cc
> +#if defined(__x86_64__) || defined(__ppc64__)
`__x86_64__` and `__ppc64__` are not compiler-independent macros. It is better to define an original macro to distinguish bit lengths (in config.h.in?).

2018-03-25 14:55 UTC, vbkaisetsu commented
I added new macros: `PRIMITIV_WORDSIZE_64` and `PRIMITIV_MAYBE_FPMATH_X87`, and enabled `-ffloat-store` option for test cases to suppress excess precision of floating points.

2018-03-27 06:54 UTC, odashi approved these changes

2018-03-27 06:55 UTC, merged