Fix a minor issue for C APIs.
primitiv/primitiv pull request #178
Opened 2018-03-28 03:16 UTC by chantera

This PR fixes a minor issue for C APIs.

2018-03-28 03:20 UTC, odashi submitted a review, later dismissed

2018-03-28 05:28 UTC, vbkaisetsu commented
Could you add a test case to validate behaviour of `primitivRepresentShapeAsString`?

2018-03-28 05:29 UTC, vbkaisetsu requested changes
Could you add a test case to validate behaviour of primitivRepresentShapeAsString?

2018-03-29 22:37 UTC, vbkaisetsu approved these changes

2018-03-29 22:38 UTC, merged

2018-03-29 22:38 UTC, vbkaisetsu commented
Thanks!