Add batch manipulation functions.
primitiv/primitiv pull request #179
Opened 2018-03-28 13:46 UTC by chantera

This PR adds following batch manipulation functions:
- `functions::batch::pick`
- `functions::batch::slice`
- `functions::batch::split`
- `functions::batch::concat`

2018-03-29 05:20 UTC, vbkaisetsu commented
Related to #175

2018-03-29 15:38 UTC, vbkaisetsu reviewed
Thank you very much.
Please check some comments.

2018-03-29 15:38 UTC, vbkaisetsu commented on primitiv/device_ops/cuda/batch_slice.cu
> +    ::atomicAdd(pgx + i, pgy[i]);
`pgx[i] += pgy[i]` ?

2018-03-29 15:38 UTC, vbkaisetsu commented on primitiv/device_ops/cuda16/batch_slice.cu
> +    ::atomicHAdd(pgx, i, ::__half2float(pgy[i]));
ditto

2018-03-29 15:38 UTC, vbkaisetsu commented on primitiv/opencl_device_kernel.cl
> +  if (i < size) atomic_add_float(pgx + i + shift, pgy[i]);
ditto

2018-04-10 20:08 UTC, odashi requested changes

2018-04-10 20:08 UTC, odashi commented on primitiv/basic_functions.h
> + * Lookups subplanes according to the batch and addresses.
(this line and others)
This function does not affect any dimensions so "subplane" looks strange.

2018-04-10 20:08 UTC, odashi commented on primitiv/basic_functions.h
> +
(this line and others)
Add `@cond` and `@endcond` directives around all undocumented functions.
https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdcond

2018-04-10 20:08 UTC, odashi commented on primitiv/cuda16_device.h
> +      const std::vector<const Tensor *> &xs, Tensor &y) override;
(this line and others)
Why newline?

2018-04-10 20:08 UTC, odashi commented on primitiv/shape_ops.h
> + * Calculates a picked shape.
(this line and others)
Description also requires information that this function is a batch operation.

2018-04-10 20:08 UTC, odashi commented on test/shape_ops_test.cc
> +     {Shape({2, 2, 2}, 3), 3, {}},
Restore original line. `{1}` is correct to evaluate the invalid operation: "pick the ID '1' from the axis with width 1."

2018-04-10 20:08 UTC, odashi commented on test/shape_ops_test.cc
> +    {Shape({2, 2, 2}, 3), {0}, Shape({2, 2, 2}, 1)},
Batch size `1` can be removed.

2018-04-10 20:08 UTC, odashi commented on test/shape_ops_test.cc
> +    {{}, {0}, {}},
Place simple test case(s) at the top of the list.

2018-04-10 20:08 UTC, odashi commented on test/shape_ops_test.cc
> +    // only a shape is invalid
a shape -> an axis

2018-04-10 20:08 UTC, odashi commented on test/tensor_forward_test.cc
> +  vector<float> x_data = make_iota_vector(3 * 2 * 3, 0);
const.

2018-04-10 20:08 UTC, odashi commented on test/tensor_forward_test.cc
> +  vector<float> x_data = make_iota_vector(3 * 3 * 4, 0);
const.

2018-04-11 17:56 UTC, chantera commented on test/shape_ops_test.cc
> +     {Shape({2, 2, 2}, 3), 3, {}},
This PR includes your commit `https://github.com/primitiv/primitiv/commit/99987e73b51e636d6271b36843f3128df3c8c3a5`.
Could you check it?

2018-04-11 20:09 UTC, odashi commented on test/shape_ops_test.cc
> +     {Shape({2, 2, 2}, 3), 3, {}},
Ah, maybe this is my fault. I should fix this by myself.

2018-04-11 20:24 UTC, odashi commented on primitiv/basic_functions.h
> + * Extracts elements according to the batch and addresses.
"Element" is a general word and has less information for users (maybe not few users could not comprehend the behavior of the function by this document).

2018-04-15 19:38 UTC, chantera commented
Fixed.

2018-04-23 14:01 UTC, odashi submitted a review, later dismissed

2018-04-23 15:08 UTC, odashi approved these changes

2018-04-25 09:45 UTC, merged