Add max() and min() functions
primitiv/primitiv pull request #182
Opened 2018-04-05 15:46 UTC by vbkaisetsu

Related to #181

This branch adds `functions::max()` and `functions::min()` functions.

When multiple elements contain a max value, gradients are back-propagated to lower indexed elements.
e.g.
```
x := [1, 2, 5, 4, 5, 2]
y := max(x, 0)
gy := [1]
The gradient of x becomes:
gx = [0, 0, 1, 0, 0, 0]
```

This branch also fixes `argmax` and `argmin` functions of `CUDA` and `OpenCL` devices that return different results from `Naive` device.

2018-04-10 16:04 UTC, chantera submitted a review, later dismissed
LGTM.

2018-04-11 12:09 UTC, odashi requested changes

2018-04-11 12:09 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
> +    const float *px, const float *py, const float *pgy,
Searching maximum values is not necessary and `py` can be utilized instead.

2018-04-11 12:09 UTC, odashi commented on primitiv/device_ops/cuda/min.cu
> +    const float *px, const float *py, const float *pgy,
Same as max.

2018-04-11 12:09 UTC, odashi commented on primitiv/device_ops/cuda16/max.cu
> +template<std::uint32_t BLOCK_SIZE>
Ditto

2018-04-11 12:09 UTC, odashi commented on primitiv/device_ops/cuda16/min.cu
> +__global__ void min_bw_dev(
Ditto

2018-04-11 12:09 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +#define MAX_BW_KERNEL(GROUP_SIZE) \
Ditto

2018-04-11 12:09 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +kernel void min_bw_kernel_##GROUP_SIZE( \
Ditto

2018-04-11 12:09 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +      if (max_val[tid + k] > max_val[tid] \
How about CUDA/CUDA16 devices?

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +        Tensor gx = dev->new_tensor_by_constant(r, 0);
`gx` == 1 is better to check whether the gradient is correctly "add"ed.

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      Tensor gx = dev->new_tensor_by_constant({n}, 0);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      Tensor gx = dev->new_tensor_by_constant({n}, 0);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      for (std::uint32_t i = 0; i < 16 && i < n; ++i) {
Need a comment about this statement and the magic number 16.

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      EXPECT_EQ(1, gx.to_vector()[pos]);
Check all values in `gx`.

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      EXPECT_EQ(1, gx.to_vector()[pos]);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      Tensor gx = dev->new_tensor_by_constant({n}, 0);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      EXPECT_EQ(1, gx.to_vector()[pos]);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      for (std::uint32_t i = 0; i < 16 && i < n; ++i) {
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      Tensor gx = dev->new_tensor_by_constant({n}, 0);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_backward_test.cc
> +      EXPECT_EQ(1, gx.to_vector()[pos]);
Ditto

2018-04-11 12:09 UTC, odashi commented on test/tensor_forward_test.cc
> +      EXPECT_TRUE(vector_match(expected[i], max(a, i).to_vector()));
Add shape checking.

2018-04-11 12:09 UTC, odashi commented on test/tensor_forward_test.cc
> +      EXPECT_EQ(n - 1, max(a, 0).to_vector()[0]);
Add shape checking.

2018-04-11 12:09 UTC, odashi commented on test/tensor_forward_test.cc
> +      EXPECT_TRUE(vector_match(expected[i], min(a, i).to_vector()));
Add shape checking.

2018-04-11 12:09 UTC, odashi commented on test/tensor_forward_test.cc
> +      EXPECT_EQ(0, min(a, 0).to_vector()[0]);
Add shape checking.

2018-04-11 12:09 UTC, odashi commented on test/tensor_test.cc
> +      EXPECT_EQ(pos, a.argmax(0)[0]);
Better to replace this to `vector_match` (existing tests should also be fixed).

2018-04-11 12:09 UTC, odashi commented on test/tensor_test.cc
> +      EXPECT_EQ(pos, a.argmin(0)[0]);
Ditto

2018-04-12 15:06 UTC, vbkaisetsu commented
Fixed.

2018-04-14 12:51 UTC, odashi requested changes
Commented only in cuda/max. Other functions should be fixed similarly.

2018-04-14 12:51 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
> +      if (temp[tid + k] > temp[tid]) { \
ditto

2018-04-14 12:51 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
> +    if (px[i * skip] == py[bid]) {
Use const variable instead of `py[bid]`.

2018-04-14 12:51 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
> +      if (argmax_val[tid + k] < argmax_val[tid]) { \
use `min` instead.

2018-04-14 12:51 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
> +    const float val = px[i * skip];
use `fmaxf` instead.

2018-04-14 14:44 UTC, vbkaisetsu commented
Fixed.

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
>    temp[tid] = FLOAT_NEGATIVE_INFINITY;
Using a local variable, and substituting it to `temp` only once at the end of the loop.

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda/min.cu
> +    temp[tid] = fminf(px[i * skip], temp[tid]);
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda16/max.cu
> +    temp[tid] = fmaxf(::__half2float(px[i * skip]), temp[tid]);
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda16/min.cu
> +    temp[tid] = fminf(::__half2float(px[i * skip]), temp[tid]);
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +    temp[tid] = max(px[i * skip], temp[tid]); \
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +    temp[tid] = min(px[i * skip], temp[tid]); \
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
> +    argmax_val[tid]
The behavior of the false-case looks redundant; maybe it is enough to use if statement.

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda/max.cu
>    argmax_val[tid] = n;
Use a local variable instead, and substitute to `argmax_val` only once.

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda/min.cu
> +    argmin_val[tid]
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda16/max.cu
> +    argmax_val[tid]
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/device_ops/cuda16/min.cu
> +    argmin_val[tid]
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +    argmax_val[tid] \
ditto

2018-04-14 17:47 UTC, odashi commented on primitiv/opencl_device_kernel.cl
> +    argmin_val[tid] \
ditto

2018-04-15 00:18 UTC, vbkaisetsu commented
Fixed.

2018-04-15 22:32 UTC, odashi approved these changes

2018-04-15 22:33 UTC, merged