Use nextafter for dealing with excess precision
primitiv/primitiv pull request #184
Opened 2018-04-10 11:42 UTC by vbkaisetsu

This branch cares for the excess floating point precision of x87 environments.

In x87 environments, a random value `x` has 32-bit precision in the memory, but has 80-bit precision in the register. Even when `x == lower` returns `false` due to the excess precision, `x` will be rounded to the `lower` bound at the outside of the *primitiv* library.

This branch uses `nextafter()` to care for values which will be rounded to the `lower` bound.

2018-04-11 20:41 UTC, odashi requested changes

2018-04-11 20:41 UTC, odashi commented on primitiv/random.h
> +      /**
This comment should not be Doxygen-ed.

2018-04-11 20:41 UTC, odashi commented on primitiv/random.h
> +      data[i] = x < std::nextafter(lower, upper) ? upper : x;
This code looks generally correct and the compiler switch and the comment are not necessary.

2018-04-11 20:41 UTC, odashi commented on primitiv/random.h
> +      data[i] = x < std::nextafter(lower, upper) ? upper : x;
Use a const variable out of the for-loop instead of directly describing `std::nextafter(lower, upper)`.

2018-04-12 10:13 UTC, vbkaisetsu commented
Fixed.

2018-04-12 11:59 UTC, odashi approved these changes

2018-04-12 12:54 UTC, merged