Fix random number generation from cuRAND normal/log_normal distributions.
primitiv/primitiv pull request #203
Opened 2018-10-29 14:05 UTC by chantera

This branch avoids exceptions caused by `CURAND_STATUS_LENGTH_NOT_MULTIPLE` error that occurs when an odd number of elements is specified for random number generation from cuRAND normal/log_normal distributions.
See the following document: https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1gb9280e447ef04e1dec4611720bd0eb69

2018-10-30 06:07 UTC, odashi requested changes

2018-10-30 06:07 UTC, odashi commented on primitiv/core/device.h
> +  static std::size_t allocated_size(const Tensor &x) {
It looks not necessary if `Tensor` provides the same public function.

2018-10-30 06:07 UTC, odashi commented on primitiv/core/memory_pool.cc
> +  if (mem_size < size) {
Is this condition necessary? `mem_size` is always largher than or equal to `size` according to `calculate_shifts`.

2018-10-30 06:07 UTC, odashi commented on primitiv/core/tensor.h
> +  std::size_t allocated_size() const { return allocated_size_; }
Let's make this function public.

2018-10-30 06:07 UTC, odashi commented on primitiv/core/tensor.h
> +  std::size_t allocated_size() const { return allocated_size_; }
Add test cases for this function.

2018-10-30 06:07 UTC, odashi commented on primitiv/core/memory_pool.cc
> +std::shared_ptr<void> MemoryPool::allocate(std::size_t size, std::size_t * const allocated_size) {
Add test cases to check `allocated_size`.

2018-10-31 17:04 UTC, chantera commented
Thank you for your review.
I fixed all.

2018-11-01 07:20 UTC, odashi commented on primitiv/devices/cuda/ops/random_log_normal.cu
>      if (capacity <= size) {
This check may always fail if the size is 1. Add some option to `MemoryPool` for allocating memories with a guarantee of minimum sizes (e.g., add `minimum_size` option to the constructor) is recommended.

2018-11-01 07:20 UTC, odashi commented on test/cuda_memory_pool_test.cc
> +}
Add more tests which checks the cases when `allocated_size` is not equal to `size`. E.g., if we try to allocate memory with 3 bytes, `MemoryPool` may set 4 into `allocated_size`.

2018-11-01 07:20 UTC, odashi commented on test/tensor_test.cc
> +      const std::size_t required_memsize
Use an additional variable for readability to store `sizeof(float or half)`.

2018-11-01 07:20 UTC, odashi commented on test/tensor_test.cc
> +TEST_F(TensorTest, CheckAllocatedSize) {
These checks should also be implemented in existing tests in this file.

2019-02-11 10:32 UTC, odashi submitted a review, later dismissed
LGTM

2019-06-16 06:50 UTC, odashi approved these changes

2019-06-18 08:10 UTC, merged